### ISSUE TITLE
Hotel instalments for a given quote

### ISSUE THREAD

**Issue by sudkumar** [tourepedia/tp-api#40]
When a trip is about the get converted, we need to provide the details about the instalments for customer, hotels and cabs. Instalments to customer depends on the instalments to the cabs and hotels. So we need to show the information about the hotels instalments for a given quote to the sales person so that this information cab be further communicated to the customer.

In order for us to be able to get the hotel instalments, we need to know the procedure of the hotel payments. Different hotels have different payment procedures like some hotel requires x% in advance (at the time of booking) and remaining at the time of check or checkout or in x interval. So first we need to store this information as a hotel's attributes and then we can do the  instalments calculation of hotels for a trip given `booking date`, `check-in` and `check-out` dates.

**Comment by sudkumar** [comment]
We have following cases for hotel pricing:

| First instalment | Second Instalment |
|-|-|
| 25%, on booking | 75%, 2 days before check-in |
| 50% , on booking | 50%, 15 days before check-in |
| 0, on booking  | 100%, 1 day before check-out |
| 50%, on booking  | 50%, 1 month before check-in |
| 40%, on booking | 60%, 7 days before check-in |
| 0, on booking  | 100% (1-15 Date Checkout on 22-25 and 16-30 Date Checkout on 7-10) |

How can we translate this to a schema ?

**Comment by sudkumar** [comment]
> Schema: **payment_preferences_for_hotels**

|Field|Type|Comments|
|-|-|-|
|id|INT|Auto increment id|
|based_on| ENUM(`booking`, `check_in`, `check_out`)|Based on which event|
|days|INT|(`+positive` = `after`, `-negative` = `before`, `0-zero` = `same day`)|
|amount|INT| How much (percentage) of the total amount on this date|
|group_by_id|uuid|To group a complete set of preferences|


> Schema: **hotel_payment_preferences**

|Field|Type|Comments|
|-|-|-|
|hotel_id|INT|Id of the hotel|
|payment_preference_group_id|INT|ID of the payment preference|
---

Let's try to store the requirements using the above two schemas. 

**payment_preferences_for_hotels**

|id|based_on|days|amount|group_by_id|
|-|-|-|-|-|
|1|booking|0|25|case_1|
|2|check_in|2|75|case_1|
|3|booking|0|50|case_2|
|4|check_in|-15|50|case_2|
|5|check_out|-1|100%|case_3|
|6|booking|0|50%|case_4|
|7|check_in|-30|50%|case_4|
|8|booking|0|40%|case_5|
|9|check_in|-7|60%|case_5|
|10|check_out|7|100%|case_7|

**case_7** is special and is not compatible with our schema. So for this, we are taking the minimum number of `safe zone day` for payment, which is, 7 days after checkout.

**Comment by ashish28ranjan** [comment]
This looks good. However, table and column names should be human readable and easy to understand. I suggest the following changes.

1. Change `based_on` to `reference`
1. Change `days` to `offset` or `day_offset`
1. Change `amount` to `amount_share`
1. Add created_at, updated_at, deleted_at and created_by columns
1. Change `check_in`, `check_out` to `checkin`, `checkout`
1. Keep `group_by_id` as second column, after `id`
1. Change `group_by_id` to `group_id`
1. Change `payment_preferences_for_hotels` to `hotel_payment_preferences_breakup`
1. Add `id` in `hotel_payment_preference`, if you believe this would be used later

These are mere suggestions. You could choose any other names if it suits better.

Case 7 is handled very smartly here!

**Comment by ashish28ranjan** [comment]
I can see in #52, that you've added a pivot table. I believe this would be redundant here.

**Comment by sudkumar** [comment]
> This looks good. However, table and column names should be human readable and easy to understand. I suggest the following changes.

These look for readable. Thanks.

**Comment by sudkumar** [comment]
@ashish28ranjan 

>  pivot table is redundant.

Assigning a column that groups the related information would suffices the requirement of grouping. But I want to show a listing of all the payment preferences in the following format:
```typescript
type PaymentPreferences = Array<{
  id: integer
  description: string // a descriptive text of all the instalments for this payment preference
  instalments: Array<{
    id: integer
    reference: "booked" | "checkin" | "checkout"
    offset: integer
    amount_share: integer
  }>
}>
```
Can we do that in a `GROUP BY` query? My guess about the `GROUP BY` query is that it will only take the first one from the database for that group. The other solution for the problem cab be, we first get all the preferences and then create a group by object in PHP.

Which would be better?

**Comment by ashish28ranjan** [comment]
You are right about `GROUP BY`. To get the data in the desired format, you'll have to use `with` relationship. And, it can be done without a pivot table. In fact, your `hotel_payment_preferences` table is a pivot between `hotels` and `hotel_payment_preference_installments`. There is no need to add another pivot table.

Define a `hasMany` relationship in the `hotel_payment_preferences` model which links to `the group_uid` of `hotel_payment_preference_installments`.

**Comment by sudkumar** [comment]
That will do 👍 

But what relationship we will use to map the preferences to a hotel? Laravel's [belongsToMany](https://laravel.com/docs/5.8/eloquent-relationships#many-to-many) does not allow us to use the `group_uid` column in the pivot table!

[hasManyThrough](https://laravel.com/docs/5.8/eloquent-relationships#has-many-through) should do the work.

```php
# App\HotelPaymentPreferences.php

protected $table = "hotel_payment_preferences`;

public function instalments () {
  return $this->hasMany(
    HotelPaymentPreferencesBreakup::class,
    "group_uid",
    "payment_preference_group_id"
  );
}
```

```php
# App\HotelPaymentPreferencesBreakup;

protected $table = "hotel_payment_preferences_breakup";

public const References = array("Booking" => 0, "Checkin" => 1, "Checkout" => 2);

public function hotels () {
  return $this->hasManyThrough(
    Hotel::class,
    HotelPaymentPreferences::class,
    "payment_preference_group_uid", // Foreign key on HotelPaymentPreferences table
    "id",  // Foreign key on Hotel table
    "group_uid", // Local key on HotelPaymentPreferencesBreakup table
    "hotel_id", // Local key on HotelPaymentPreferences
  );
}

```

```php
# App\Hotel.php

public function paymentPreferences () {
  return $this->hasManyThrough(
    HotelPaymentPreferencesBreakup::class,
    HotelPaymentPreferences::class,
    "hotel_id", // Foreign key on HotelPaymentPreferences table
    "group_uid",  // Foreign key on HotelPaymentPreferencesBreakup table
    "id", // Local key on Hotel table
    "payment_preference_group_uid", // Local key on HotelPaymentPreferences
  );
}
```


Any thoughts? Or could we make it a bit simpler?

**Comment by ashish28ranjan** [comment]
Good to go!

**Comment by sudkumar** [comment]
@ashish28ranjan  Noop. We got a problem here.

Basically, We gonna have a list of payment preferences for all the hotels, seeded in the database. In that case, our `hasMany` relationship will return empty results because the preferences are not mapped to any hotel. I think we need to have a grouping table.
